# Generated by ‘nixos-generate-config’, then hand-edited for impermanence:
# the fileSystems block below no longer matches what a regenerated file would
# contain, so do NOT blindly overwrite it. See the comment on fileSystems."/".
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Impermanence: / is the "root" subvolume, wiped on every boot by
  # manual-modules/impermanence. It used to be the btrfs top-level (subvolid=5),
  # which cannot be deleted and recreated. /home is deliberately NOT a separate
  # subvolume any more -- it lives inside the wiped root, and only the paths
  # listed in manual-modules/impermanence/home.nix survive.
  fileSystems."/" = {
    device = "/dev/mapper/luks-7fbde2fd-f08a-430a-86cf-8b0940d13df5";
    fsType = "btrfs";
    options = ["subvol=root" "noatime"];
  };

  boot.initrd.luks.devices."luks-7fbde2fd-f08a-430a-86cf-8b0940d13df5".device = "/dev/disk/by-uuid/7fbde2fd-f08a-430a-86cf-8b0940d13df5";

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-7fbde2fd-f08a-430a-86cf-8b0940d13df5";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime"];
  };

  # neededForBoot is set in manual-modules/impermanence.
  fileSystems."/persist" = {
    device = "/dev/mapper/luks-7fbde2fd-f08a-430a-86cf-8b0940d13df5";
    fsType = "btrfs";
    options = ["subvol=persist" "noatime"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/31A4-4D31";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
